# 개발 환경 설정
server:
  port: 8080

spring:
  profiles:
    active: dev

# 개발용 토큰 제한 (관대한 설정)
token:
  limit:
    vllm-url: http://localhost:8000
    max-tokens-per-minute: 5000
    max-tokens-per-hour: 50000
    max-tokens-per-day: 500000
    max-concurrent-requests: 20

# 개발용 Redis (로컬)
spring.data.redis:
  host: localhost
  port: 6379

# 상세한 로깅
logging:
  level:
    com.example.simpletokenlimiter: DEBUG
    org.springframework.web: DEBUG
    reactor: DEBUG
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

# 개발용 액추에이터 (모든 엔드포인트 노출)
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      show-values: always
    configprops:
      show-values: always
  # Spring Boot 3.x 새로운 prometheus 설정
  prometheus:
    metrics:
      export:
        enabled: true