server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: simple-token-limiter
  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 2000ms
  
  lifecycle:
    timeout-per-shutdown-phase: 30s

# 토큰 제한 설정 (Llama 3.2 1B 전용)
token:
  limit:
    model-name: llama3.2-1b
    vllm-url: ${VLLM_URL:http://localhost:8000}
    max-tokens-per-minute: ${MAX_TOKENS_MINUTE:1000}
    max-tokens-per-hour: ${MAX_TOKENS_HOUR:10000}
    max-tokens-per-day: ${MAX_TOKENS_DAY:100000}
    max-concurrent-requests: ${MAX_CONCURRENT:5}

# 액추에이터 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  # Spring Boot 3.x 새로운 prometheus 설정 방식
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${ENVIRONMENT:development}

# 로깅 설정
logging:
  level:
    com.example.simpletokenlimiter: ${LOG_LEVEL:INFO}
    org.springframework.data.redis: WARN
    io.lettuce: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"